"nodejs";
const path = require('path')
const fs = require('fs')
const ne_app_node_js_rj = require("./ne-1.js")
const tsjq_yxna_hfbc = require('../scripts/tsjq-yxna-hfbc.js')
const app_node_outFile = path.resolve('app.node.js')
const app_node_outText = ne_app_node_js_rj()
fs.writeFileSync(app_node_outFile, app_node_outText)
console.log(`'Done - make app-node-js. See'${app_node_outFile}`)
tsjq_yxna_hfbc(__dirname + '/tsjq')