const fs = require('fs')
const stat_1 = fs.statSync('app.js')
const stat_2 = fs.statSync('app.node.js')
const stat_yrds = fs.statSync('./auto/yrds.js')
console.assert(stat_1.ctimeMs<stat_2.ctimeMs,`app.node.js ra ymce.` )
console.assert(stat_yrds.ctimeMs<stat_2.ctimeMs,`app.node.js ra ymce.`)
console.log('Done.')